/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Diagnostic =
  | {
      kind: "analyzer_unavailable";
      message: string;
      severity: string;
      [k: string]: unknown;
    }
  | {
      kind: "analyzer_contract_mismatch";
      message: string;
      severity: string;
      [k: string]: unknown;
    }
  | {
      kind: "analyzer_issue";
      message: string;
      severity: string;
      span?: SourceSpan | null;
      [k: string]: unknown;
    }
  | {
      file_ids: string[];
      id: string;
      kind: "payload_identity_conflict";
      message: string;
      name: string;
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "unreadable_file";
      message: string;
      path: string;
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "failed_file";
      message: string;
      path: string;
      [k: string]: unknown;
    }
  | {
      kind: "warning";
      message: string;
      span?: SourceSpan | null;
      [k: string]: unknown;
    }
  | {
      file_id: string;
      id: string;
      kind: "membership_conflict";
      message: string;
      modules: string[];
      path: string;
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "dangling_reference";
      message: string;
      missing_entity_id: string;
      relationship_id: string;
      [k: string]: unknown;
    }
  | {
      file_id?: string | null;
      id: string;
      kind: "coverage";
      message: string;
      [k: string]: unknown;
    }
  | {
      evidence_id: string;
      id: string;
      kind: "stale_evidence";
      message: string;
      [k: string]: unknown;
    }
  | {
      file_id: string;
      id: string;
      kind: "source_unavailable";
      message: string;
      path: string;
      [k: string]: unknown;
    };
export type Evidence =
  | {
      id: string;
      kind: "source";
      span: SourceSpan;
      [k: string]: unknown;
    }
  | {
      content_hash: string;
      id: string;
      kind: "source_snapshot";
      span: SourceSpan;
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "text";
      value: string;
      [k: string]: unknown;
    }
  | {
      analyzer: string;
      confidence?: string | null;
      detail: string;
      id: string;
      kind: "analyzer";
      origin?: string | null;
      rule?: string | null;
      /**
       * Every source site supporting the relationship, e.g. each call of one callee.
       */
      sites?: SourceSpan[];
      [k: string]: unknown;
    };
export type Finding =
  | {
      affected_entity_ids?: string[];
      affected_file_ids?: string[];
      id: string;
      kind: "rule";
      message: string;
      navigation_target: NavigationTarget;
      relationship_ids?: string[];
      rule_id: string;
      supporting_sites?: SourceSpan[];
      [k: string]: unknown;
    }
  | {
      entity_id: string;
      kind: "entity";
      message: string;
      [k: string]: unknown;
    }
  | {
      kind: "relationship";
      message: string;
      relationship_id: string;
      [k: string]: unknown;
    }
  | {
      kind: "project";
      message: string;
      [k: string]: unknown;
    };
export type InventoryOutcome =
  | {
      kind: "included";
      [k: string]: unknown;
    }
  | {
      kind: "excluded";
      rule: string;
      [k: string]: unknown;
    }
  | {
      kind: "unsupported";
      [k: string]: unknown;
    }
  | {
      io_error: string;
      kind: "unreadable";
      [k: string]: unknown;
    }
  | {
      diagnostic_id: string;
      kind: "failed";
      [k: string]: unknown;
    };
export type Relationship =
  | {
      evidence_id?: string | null;
      id: string;
      kind: "imports";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "references";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "calls";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "contains";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "depends_on";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "handles";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "persists";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "transforms";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "consumes";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "produces";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "dispatches";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    }
  | {
      evidence_id?: string | null;
      id: string;
      kind: "invokes_prompt";
      origin: string;
      source: string;
      target: string;
      [k: string]: unknown;
    };
export type ScopeChild =
  | {
      kind: "directory";
      scope_id: string;
      [k: string]: unknown;
    }
  | {
      file_id: string;
      kind: "file";
      scope_id: string;
      [k: string]: unknown;
    }
  | {
      kind: "module";
      module_id: string;
      scope_id: string;
      [k: string]: unknown;
    }
  | {
      entity_id: string;
      kind: "symbol";
      scope_id?: string | null;
      [k: string]: unknown;
    };
export type AnalysisStatus =
  | {
      kind: "none";
      [k: string]: unknown;
    }
  | {
      kind: "unsupported";
      [k: string]: unknown;
    }
  | {
      analyzer: string;
      kind: "parsed";
      [k: string]: unknown;
    }
  | {
      kind: "failed";
      message: string;
      [k: string]: unknown;
    };

export interface Snapshot {
  claims?: Claim[];
  diagnostics?: Diagnostic[];
  entities?: CodeEntity[];
  evidence?: Evidence[];
  findings?: Finding[];
  forbidden_dependencies?: ForbiddenDependencyRule[];
  manifest: Manifest;
  modules?: LogicalModule[];
  payload_contracts?: PayloadContract[];
  projections?: Projection[];
  relationships?: Relationship[];
  scope_index?: ScopeIndex | null;
  source_files?: SourceFile[];
  unresolved_references?: UnresolvedReference[];
  [k: string]: unknown;
}
export interface Claim {
  evidence_ids?: string[];
  id: string;
  object: unknown;
  predicate: string;
  subject: string;
  [k: string]: unknown;
}
export interface SourceSpan {
  end_column: number;
  end_line: number;
  file_id: string;
  start_column: number;
  start_line: number;
  [k: string]: unknown;
}
export interface CodeEntity {
  attributes?: {
    [k: string]: unknown;
  };
  declaration_kind: string;
  file_id: string;
  id: string;
  is_local?: boolean;
  name: string;
  owner_id?: string | null;
  qualified_name: string;
  scope_id: string;
  span: SourceSpan;
  [k: string]: unknown;
}
export interface NavigationTarget {
  entity_id?: string | null;
  scope_id: string;
  [k: string]: unknown;
}
export interface ForbiddenDependencyRule {
  from: string;
  to: string;
  [k: string]: unknown;
}
export interface Manifest {
  analyzer_versions?: {
    [k: string]: string;
  };
  config_snapshot?: {
    [k: string]: unknown;
  };
  files?: string[];
  inventory: InventoryCounts;
  inventory_entries?: InventoryEntry[];
  repository: string;
  root: string;
  root_scope_id: string;
  scanned_at: string;
  schema_version: string;
  source_included?: boolean;
  tool_version: string;
  validation?: ValidationSummary;
  [k: string]: unknown;
}
export interface InventoryCounts {
  excluded: number;
  failed: number;
  included: number;
  unreadable: number;
  unsupported: number;
  [k: string]: unknown;
}
export interface InventoryEntry {
  outcome: InventoryOutcome;
  path: string;
  [k: string]: unknown;
}
export interface ValidationSummary {
  diagnostics: number;
  errors: number;
  warnings: number;
  [k: string]: unknown;
}
export interface LogicalModule {
  entity_ids?: string[];
  file_ids?: string[];
  id: string;
  name: string;
  scope_id: string;
  selectors?: string[];
  tags?: string[];
  [k: string]: unknown;
}
export interface PayloadContract {
  consumer_ids?: string[];
  name: string;
  producer_ids?: string[];
  schema?: unknown;
  [k: string]: unknown;
}
export interface Projection {
  entity_ids?: string[];
  id: string;
  kind?: string;
  name: string;
  parent_scope_id?: string | null;
  relationship_ids?: string[];
  scope_id: string;
  tags?: string[];
  [k: string]: unknown;
}
export interface ScopeIndex {
  scopes: ScopeSlice[];
  [k: string]: unknown;
}
export interface ScopeSlice {
  child_scope_ids?: string[];
  children: ScopeChild[];
  crossing_relationship_ids: string[];
  owner_map: {
    [k: string]: string;
  };
  scope_id: string;
  [k: string]: unknown;
}
export interface SourceFile {
  analysis: AnalysisStatus;
  byte_length?: number | null;
  content_hash?: string | null;
  id: string;
  language?: string | null;
  line_count?: number | null;
  path: string;
  [k: string]: unknown;
}
export interface UnresolvedReference {
  name: string;
  reason?: string | null;
  source: string;
  span: SourceSpan;
  [k: string]: unknown;
}
