#!/usr/bin/env node

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

interface Options {
  output: string;
  relationships: number;
  files: number;
  entities: number;
  seed: number;
}

const options = parseOptions(process.argv.slice(2));
const output = resolve(options.output);
mkdirSync(output, { recursive: true });
mkdirSync(join(output, "source"), { recursive: true });

const fixture = generateFixture(options.relationships, options.seed);
writeFileSync(join(output, "fixture.json"), `${JSON.stringify(fixture)}\n`);
writeFileSync(join(output, "source", "sysvista.toml"), "[repository]\nname = \"scale-fixture\"\n\n[[modules]]\nname = \"services\"\nselectors = [\"pkg-*/src/services/**\"]\n");
for (const source of generateSources(options.files, options.entities, options.relationships, options.seed)) {
  const path = join(output, "source", source.name);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, source.contents);
}

process.stdout.write(`${JSON.stringify({
  fixture: join(output, "fixture.json"),
  relationships: options.relationships,
  files: options.files,
  entities: options.entities,
  seed: options.seed,
  source: join(output, "source"),
})}\n`);

function generateFixture(relationshipCount: number, seed: number) {
  const random = xorshift32(seed);
  const childCount = 3;
  const leafCount = 6;
  const children = Array.from({ length: childCount }, (_, index) => entity(
    `child-${index}`,
    `Child${index}`,
    "module",
    "root",
    index + 1,
  ));
  const leaves = Array.from({ length: leafCount }, (_, index) => {
    const owner = index % childCount;
    return {
      ...entity(`leaf-${index}`, `Leaf${index}`, "function", `child-${owner}-scope`, childCount + index + 1),
      owner_id: `child-${owner}`,
    };
  });
  const ownerMap = Object.fromEntries(leaves.map((leaf) => [leaf.id, leaf.owner_id]));
  const relationships = Array.from({ length: relationshipCount }, (_, index) => {
    const sourceIndex = Math.floor(random() * leafCount);
    const sourceOwner = sourceIndex % childCount;
    let targetIndex = Math.floor(random() * leafCount);
    if (targetIndex % childCount === sourceOwner) targetIndex = (targetIndex + 1) % leafCount;
    return {
      id: `relationship-${index}`,
      kind: index % 5 === 0 ? "references" : "calls",
      source: `leaf-${sourceIndex}`,
      target: `leaf-${targetIndex}`,
      origin: "resolved",
    };
  });
  return {
    seed,
    relationship_count: relationshipCount,
    snapshot: {
      manifest: {
        schema_version: "3",
        root_scope_id: "root",
        repository: "scale-fixture",
        scanned_at: "2000-01-01T00:00:00Z",
        root: "/scale-fixture",
        tool_version: "generated",
        inventory: { included: 1, excluded: 0, unsupported: 0, unreadable: 0, failed: 0 },
      },
      source_files: [{ id: "scale-file", path: "fixture.ts", language: "typescript", analysis: { kind: "parsed", analyzer: "synthetic" } }],
      entities: [...children, ...leaves],
      relationships,
    },
    index: {
      scopes: [{
        scope_id: "root",
        children: children.map(({ id }) => ({ kind: "symbol", entity_id: id, scope_id: `${id}-scope` })),
        child_scope_ids: children.map(({ id }) => `${id}-scope`),
        owner_map: ownerMap,
        crossing_relationship_ids: relationships.map(({ id }) => id),
      }],
    },
  };
}

function generateSources(fileCount: number, entityCount: number, relationshipCount: number, seed: number): Array<{ name: string; contents: string }> {
  const random = xorshift32(seed);
  const sources = [];
  const functionsPerFile = Math.max(2, Math.ceil(entityCount / fileCount));
  const callsPerFile = Math.ceil(relationshipCount / fileCount);
  for (let fileIndex = 0; fileIndex < fileCount; fileIndex += 1) {
    const packageNumber = Math.floor(fileIndex / 100);
    const part = `pkg-${String(packageNumber).padStart(3, "0")}`;
    const lines = ["// Generated by scripts/gen-scale-fixture.ts; do not commit."];
    for (let index = 0; index < functionsPerFile; index += 1) {
      const value = Math.floor(random() * 1_000_000_000);
      const calls = Array.from({ length: Math.floor(callsPerFile / functionsPerFile) + (index < callsPerFile % functionsPerFile ? 1 : 0) },
        (_, call) => `target${(index + call + 1) % functionsPerFile}()`);
      lines.push(`export function target${index}(): number { return ${[String(value), ...calls].join(" + ")}; }`);
    }
    lines.push(`export class Container${fileIndex} {`, "  nested() { return target0(); }", "}");
    sources.push({ name: `${part}/src/services/service-${String(fileIndex).padStart(5, "0")}.ts`, contents: lines.join("\n") });
    if (fileIndex % 100 === 0) {
      sources.push({ name: `${part}/package.json`, contents: JSON.stringify({ name: part, version: "1.0.0", type: "module" }) });
      sources.push({ name: `${part}/tsconfig.json`, contents: JSON.stringify({
        compilerOptions: { target: "ES2022", module: "NodeNext", moduleResolution: "NodeNext", noEmit: true, skipLibCheck: true },
        include: ["src/**/*.ts"],
      }) });
    }
  }
  return sources;
}

function entity(id: string, name: string, declarationKind: string, scopeId: string, line: number) {
  return {
    id,
    name,
    qualified_name: name,
    declaration_kind: declarationKind,
    file_id: "scale-file",
    scope_id: scopeId,
    span: { file_id: "scale-file", start_line: line, start_column: 1, end_line: line, end_column: 2 },
  };
}

function xorshift32(seed: number): () => number {
  let state = seed >>> 0 || 0x9e3779b9;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 0x1_0000_0000;
  };
}

function parseOptions(arguments_: string[]): Options {
  const values = new Map<string, string>();
  for (let index = 0; index < arguments_.length; index += 2) {
    const key = arguments_[index];
    const value = arguments_[index + 1];
    if (!key?.startsWith("--") || value === undefined) usage();
    values.set(key.slice(2), value);
  }
  const output = values.get("output");
  const relationships = Number(values.get("relationships"));
  const seed = Number(values.get("seed") ?? "1");
  const files = Number(values.get("files") ?? Math.max(1, Math.ceil(relationships / 25)));
  const entities = Number(values.get("entities") ?? files * 10);
  if (!output || !Number.isSafeInteger(relationships) || relationships < 1 || !Number.isSafeInteger(seed)
    || !Number.isSafeInteger(files) || files < 1 || !Number.isSafeInteger(entities) || entities < files) usage();
  return { output, relationships, files, entities, seed };
}

function usage(): never {
  process.stderr.write("usage: node scripts/gen-scale-fixture.ts --files <count> --entities <count> --relationships <count> --seed <integer> --output <directory>\n");
  process.exit(2);
}
